on:
  workflow_dispatch:
name: Live recording split

env:
  BUCKET_IN: 1y0wC3gPNYJzUybbGDcnOA7GRR-8tTN_5
  BUCKET_OUT: 1Od93No5XJ6Q_FMokWoGwIGamE7x4qhwT

jobs:
  initsrc:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup build matrix
      id: set-matrix
      run: |
        python build_matrix_split.py 
        JSON=$(cat ./matrix.json)
        JSON="${JSON//'%'/%25}"
        JSON="${JSON//$'\n'/%0A}"
        JSON="${JSON//$'\r'/%0D}"
        echo "::set-output name=matrix::${JSON}"
  render:
    needs: initsrc
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.initsrc.outputs.matrix)}}
      fail-fast: false
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-go@v3
    - name: Install gdrive CLI
      run: go install github.com/prasmussen/gdrive@latest
    - name: Configure credential for gdrive CLI
      run: echo $GDRIVE_CREDENTIAL > ~/.gdrive/token_v2.json
      env: # Or as an environment variable
        GDRIVE_CREDENTIAL: ${{ secrets.GDRIVE_CREDENTIAL }}
    - name: Install packages
      run: |
        sudo apt update
        sudo apt install -yq ffmpeg
    - name: Download video file
      run: |
        gdrive download ${{ matrix.source }}
    - name: Split video
      run: |
        ffmpeg -ss ${{ matrix.time_from }} -i ${{matrix.source_file}} -to ${{ matrix.time_to }} -c copy -copyts -avoid_negative_ts make_zero video_${{matrix.output}}
    - name: Join image and video
      run: |
        ffmpeg \
          -loop 1 -framerate 24 -t 1 -i ${{matrix.title_image}} \
          -i video_${{matrix.output}} \
          -f lavfi -t 0.1 -i anullsrc=channel_layout=stereo:sample_rate=44100 \
          -filter_complex "[0:v][2:a][1:v][1:a]concat=n=2:v=1:a=1" ${{matrix.output}}
    - name: Upload rendered video file
      run: | 
        gdrive upload -p ${{env.BUCKET_OUT}} ${{matrix.output}}

